# Generated by Django 4.2.5 on 2023-09-06 20:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='text',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.text'),
        ),
        migrations.AlterField(
            model_name='notification',
            name='action',
            field=models.CharField(choices=[('create', 'Create'), ('update', 'Update'), ('delete', 'Delete')], max_length=10),
        ),
    ]
