# Generated by Django 4.2.5 on 2023-09-07 05:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_email_text_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='text',
            name='email',
            field=models.CharField(max_length=255),
        ),
        migrations.DeleteModel(
            name='Email',
        ),
    ]
