# Generated by Django 4.2.5 on 2023-09-07 05:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_remove_text_created_at_remove_text_email_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='text',
            name='email',
            field=models.CharField(default=None, max_length=255),
        ),
    ]
